//HintName: IVariousTypesTools.PropertyNames.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace CSharpToJsonSchema.IntegrationTests
{
    public partial class VariousTypesToolsExtensionsJsonSerializerContext
    {
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Parameter1 = global::System.Text.Json.JsonEncodedText.Encode("Parameter1");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Parameter2 = global::System.Text.Json.JsonEncodedText.Encode("Parameter2");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Parameter3 = global::System.Text.Json.JsonEncodedText.Encode("Parameter3");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Parameter4 = global::System.Text.Json.JsonEncodedText.Encode("Parameter4");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Parameter5 = global::System.Text.Json.JsonEncodedText.Encode("Parameter5");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_DateTime = global::System.Text.Json.JsonEncodedText.Encode("DateTime");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Date = global::System.Text.Json.JsonEncodedText.Encode("Date");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Value = global::System.Text.Json.JsonEncodedText.Encode("Value");
    }
}
