//HintName: IWeatherTools.GetJsonTypeInfo.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace CSharpToJsonSchema.IntegrationTests
{
    public partial class WeatherToolsExtensionsJsonSerializerContext : global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver
    {
        /// <inheritdoc/>
        public override global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetTypeInfo(global::System.Type type)
        {
            Options.TryGetTypeInfo(type, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? typeInfo);
            return typeInfo;
        }

        global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver.GetTypeInfo(global::System.Type type, global::System.Text.Json.JsonSerializerOptions options)
        {
            if (type == typeof(double))
            {
                return Create_Double(options);
            }
            if (type == typeof(global::CSharpToJsonSchema.IntegrationTests.GetCurrentWeatherArgs))
            {
                return Create_GetCurrentWeatherArgs(options);
            }
            if (type == typeof(global::CSharpToJsonSchema.IntegrationTests.GetCurrentWeatherAsyncArgs))
            {
                return Create_GetCurrentWeatherAsyncArgs(options);
            }
            if (type == typeof(global::CSharpToJsonSchema.IntegrationTests.Unit))
            {
                return Create_Unit(options);
            }
            if (type == typeof(global::CSharpToJsonSchema.IntegrationTests.Weather))
            {
                return Create_Weather(options);
            }
            if (type == typeof(string))
            {
                return Create_String(options);
            }
            return null;
        }
    }
}
