//HintName: ToolsJsonSerializerContext.GetJsonTypeInfo.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace CSharpToJsonSchema.IntegrationTests
{
    public partial class ToolsJsonSerializerContext : global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver
    {
        /// <inheritdoc/>
        public override global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetTypeInfo(global::System.Type type)
        {
            Options.TryGetTypeInfo(type, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? typeInfo);
            return typeInfo;
        }

        global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver.GetTypeInfo(global::System.Type type, global::System.Text.Json.JsonSerializerOptions options)
        {
            if (type == typeof(global::CSharpToJsonSchema.IntegrationTests.SampleFunctionTool_NoReturnAsyncArgs))
            {
                return Create_SampleFunctionTool_NoReturnAsyncArgs(options);
            }
            if (type == typeof(global::CSharpToJsonSchema.IntegrationTests.SampleFunctionTool_Static_NoReturnAsyncArgs))
            {
                return Create_SampleFunctionTool_Static_NoReturnAsyncArgs(options);
            }
            if (type == typeof(global::CSharpToJsonSchema.IntegrationTests.SampleFunctionTool_Static_StringArgs))
            {
                return Create_SampleFunctionTool_Static_StringArgs(options);
            }
            if (type == typeof(global::CSharpToJsonSchema.IntegrationTests.SampleFunctionTool_Static_StringAsyncArgs))
            {
                return Create_SampleFunctionTool_Static_StringAsyncArgs(options);
            }
            if (type == typeof(global::CSharpToJsonSchema.IntegrationTests.SampleFunctionTool_Static_VoidArgs))
            {
                return Create_SampleFunctionTool_Static_VoidArgs(options);
            }
            if (type == typeof(global::CSharpToJsonSchema.IntegrationTests.SampleFunctionTool_StringArgs))
            {
                return Create_SampleFunctionTool_StringArgs(options);
            }
            if (type == typeof(global::CSharpToJsonSchema.IntegrationTests.SampleFunctionTool_StringAsyncArgs))
            {
                return Create_SampleFunctionTool_StringAsyncArgs(options);
            }
            if (type == typeof(global::CSharpToJsonSchema.IntegrationTests.SampleFunctionTool_VoidArgs))
            {
                return Create_SampleFunctionTool_VoidArgs(options);
            }
            if (type == typeof(string))
            {
                return Create_String(options);
            }
            return null;
        }
    }
}
