//HintName: IVariousTypesTools.DateOnly.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace CSharpToJsonSchema.IntegrationTests
{
    public partial class VariousTypesToolsExtensionsJsonSerializerContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.DateOnly>? _DateOnly;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        #nullable disable annotations // Marking the property type as nullable-oblivious.
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.DateOnly> DateOnly
        #nullable enable annotations
        {
            get => _DateOnly ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.DateOnly>)Options.GetTypeInfo(typeof(global::System.DateOnly));
        }
        
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.DateOnly> Create_DateOnly(global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::System.DateOnly>(options, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.DateOnly> jsonTypeInfo))
            {
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<global::System.DateOnly>(options, global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.DateOnlyConverter);
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }
    }
}
