//HintName: IWeatherTools.PropertyNames.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace CSharpToJsonSchema.IntegrationTests
{
    public partial class WeatherToolsExtensionsJsonSerializerContext
    {
        private static readonly global::System.Text.Json.JsonEncodedText PropName_location = global::System.Text.Json.JsonEncodedText.Encode("location");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_unit = global::System.Text.Json.JsonEncodedText.Encode("unit");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_temperature = global::System.Text.Json.JsonEncodedText.Encode("temperature");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_description = global::System.Text.Json.JsonEncodedText.Encode("description");
    }
}
