//HintName: ToolsJsonSerializerContext.PropertyNames.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace CSharpToJsonSchema.IntegrationTests
{
    public partial class ToolsJsonSerializerContext
    {
        private static readonly global::System.Text.Json.JsonEncodedText PropName_input = global::System.Text.Json.JsonEncodedText.Encode("input");
    }
}
