//HintName: IWeatherStrictTools.PropertyNames.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace CSharpToJsonSchema.IntegrationTests
{
    public partial class WeatherStrictToolsExtensionsJsonSerializerContext
    {
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Location = global::System.Text.Json.JsonEncodedText.Encode("Location");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Unit = global::System.Text.Json.JsonEncodedText.Encode("Unit");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Temperature = global::System.Text.Json.JsonEncodedText.Encode("Temperature");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Description = global::System.Text.Json.JsonEncodedText.Encode("Description");
    }
}
