//HintName: ToolsJsonSerializerContext.SampleFunctionTool_StringAsyncArgs.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace CSharpToJsonSchema.IntegrationTests
{
    public partial class ToolsJsonSerializerContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::CSharpToJsonSchema.IntegrationTests.SampleFunctionTool_StringAsyncArgs>? _SampleFunctionTool_StringAsyncArgs;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        #nullable disable annotations // Marking the property type as nullable-oblivious.
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::CSharpToJsonSchema.IntegrationTests.SampleFunctionTool_StringAsyncArgs> SampleFunctionTool_StringAsyncArgs
        #nullable enable annotations
        {
            get => _SampleFunctionTool_StringAsyncArgs ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::CSharpToJsonSchema.IntegrationTests.SampleFunctionTool_StringAsyncArgs>)Options.GetTypeInfo(typeof(global::CSharpToJsonSchema.IntegrationTests.SampleFunctionTool_StringAsyncArgs));
        }
        
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::CSharpToJsonSchema.IntegrationTests.SampleFunctionTool_StringAsyncArgs> Create_SampleFunctionTool_StringAsyncArgs(global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::CSharpToJsonSchema.IntegrationTests.SampleFunctionTool_StringAsyncArgs>(options, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::CSharpToJsonSchema.IntegrationTests.SampleFunctionTool_StringAsyncArgs> jsonTypeInfo))
            {
                var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::CSharpToJsonSchema.IntegrationTests.SampleFunctionTool_StringAsyncArgs>
                {
                    ObjectCreator = () => new global::CSharpToJsonSchema.IntegrationTests.SampleFunctionTool_StringAsyncArgs(),
                    ObjectWithParameterizedConstructorCreator = null,
                    PropertyMetadataInitializer = _ => SampleFunctionTool_StringAsyncArgsPropInit(options),
                    ConstructorParameterMetadataInitializer = null,
                    ConstructorAttributeProviderFactory = static () => typeof(global::CSharpToJsonSchema.IntegrationTests.SampleFunctionTool_StringAsyncArgs).GetConstructor(InstanceMemberBindingFlags, binder: null, global::System.Array.Empty<global::System.Type>(), modifiers: null),
                    SerializeHandler = SampleFunctionTool_StringAsyncArgsSerializeHandler,
                };
                
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::CSharpToJsonSchema.IntegrationTests.SampleFunctionTool_StringAsyncArgs>(options, objectInfo);
                jsonTypeInfo.NumberHandling = null;
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[] SampleFunctionTool_StringAsyncArgsPropInit(global::System.Text.Json.JsonSerializerOptions options)
        {
            var properties = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[1];

            var info0 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<string>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::CSharpToJsonSchema.IntegrationTests.SampleFunctionTool_StringAsyncArgs),
                Converter = null,
                Getter = static obj => ((global::CSharpToJsonSchema.IntegrationTests.SampleFunctionTool_StringAsyncArgs)obj).Input,
                Setter = static (obj, value) => ((global::CSharpToJsonSchema.IntegrationTests.SampleFunctionTool_StringAsyncArgs)obj).Input = value!,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Input",
                JsonPropertyName = null,
                AttributeProviderFactory = static () => typeof(global::CSharpToJsonSchema.IntegrationTests.SampleFunctionTool_StringAsyncArgs).GetProperty("Input", InstanceMemberBindingFlags, null, typeof(string), global::System.Array.Empty<global::System.Type>(), null),
            };
            
            properties[0] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<string>(options, info0);

            return properties;
        }

        // Intentionally not a static method because we create a delegate to it. Invoking delegates to instance
        // methods is almost as fast as virtual calls. Static methods need to go through a shuffle thunk.
        private void SampleFunctionTool_StringAsyncArgsSerializeHandler(global::System.Text.Json.Utf8JsonWriter writer, global::CSharpToJsonSchema.IntegrationTests.SampleFunctionTool_StringAsyncArgs? value)
        {
            if (value is null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartObject();

            string __value_Input = ((global::CSharpToJsonSchema.IntegrationTests.SampleFunctionTool_StringAsyncArgs)value).Input;
            if (__value_Input is not null)
            {
                writer.WriteString(PropName_input, __value_Input);
            }

            writer.WriteEndObject();
        }
    }
}
